version: '3'


services:
  nestjsapp:
    image: gsharma807/nestjsapp
    restart: always
    container_name: nestjsapp
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  mongodbapp:
      image: mongo:latest
      environment:
        - MONGODB_DATABASE="auctionDB"
      ports:
        - 27017:27017
      depends_on:
        - nestjs-app
      networks:
          - app-network

networks:
  app-network:
    driver: bridge