version: '3'

services:
  nestjs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/auction

  mongo:
    image: mongo
    ports:
      - "27017:27017"