version: '3'


services:
  nestjs-app:
    restart: always
    container_name: nestjs-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
      - NODE_ENV=production

  mongodbapp:
      image: mongo:latest
      environment:
        - MONGODB_DATABASE="auctionDB"
      ports:
        - 27017:27017