name: Publish Docker Image

on:
  push:
    branches: ['master']

env:
  app-name: auctionapp


jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - run: npm install
      - run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gsharma807/auctionrepo

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: List files in root directory
        run: ls -al

      - name: Run Docker Compose
        run: docker-compose -f ./docker-compose.yml up -d --build

      - name: Configure Docker to authenticate with GCR
        run: gcloud auth configure-docker
      
      - name: Pull Docker image from Docker Hub
        run: docker pull gsharma807/auctionrepo:latest

      - name: Tag Docker image for GCR
        run: docker tag gsharma807/auctionrepo:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/gsharma807/auctionrepo:latest

      - name: Push Docker image to GCR
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/gsharma807/auctionrepo:latest

      - name: Deploy to Cloud Run
        run: gcloud run deploy auction-app --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/gsharma807/auctionrepo:latest --platform=managed --region=us-central1