name: Publish Docker Image

on:
  push:
    branches: ['master']

env:
  app-name: auctionapp


jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Npm Install
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Docker compose
        run: docker-compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Docker meta for NestJS Service
        id: nestjsapp-meta
        uses: docker/metadata-action@v5
        with:
            images: gsharma807/nestjsapp
      
      # - name: Build and push MongoDB image
      #   run: |
      #     docker build -t gsharma807/mongodbapp:latest .
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      #     docker push gsharma807/mongodbapp:latest
  
      - name: Build and push NestJS image
        run: |
          docker build -t gsharma807/nestjsapp:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push gsharma807/nestjsapp:latest

      # - name: Tag and push Docker images
      #   run: |
      #     docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      #     docker-compose push

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to authenticate with GCR
        run: gcloud auth configure-docker

      - name: Pull MongoDB image from Docker Hub
        run: docker pull mongo:latest
      
      - name: Pull Nest JS Docker image from Docker Hub
        run: docker pull gsharma807/nestjsapp:latest

      - name: Tag Docker image for GCR
        run: |
          docker tag mongo:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/mongodbapp:latest
          docker tag gsharma807/nestjsapp:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/nestjsapp:latest

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/mongodbapp:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nestjsapp:latest

      # - name: Deploy to Cloud Run
      #   run: gcloud run deploy auction-app --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/gsharma807/auctionrepo:latest --platform=managed --region=us-central1

      - name: Deploy MongoDB App to Google Cloud Run
        run: |
          gcloud run deploy mongo-service \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/mongodbapp:latest \
            --platform=managed \
            --region=us-central1 \
            --port=27017 \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy NestJS App to Google Cloud Run
        run: |
          gcloud run deploy nestjs-service \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/nestjsapp:latest \
            --platform=managed \
            --region=us-central1 \
            --port=3000 \
            --project=${{ secrets.GCP_PROJECT_ID }}